# Generated by Django 4.2.4 on 2023-11-30 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('value', models.FloatField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='trivagoHotel/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hotel_brand', to='trivagoHotel.brand')),
            ],
        ),
    ]
