# Generated by Django 4.2.4 on 2023-12-01 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivagoHotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='desc',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='model',
            field=models.CharField(max_length=600),
        ),
    ]
