# Generated by Django 4.2.4 on 2023-09-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivagoHotel', '0002_brand_alter_room_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='plate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
